2022-dimipay-recruit/WEB-Backend

prisma/schema.prisma, recruit.sql, src/interfaces/index.ts, src/interfaces/question.ts, src/types/index.ts
* id : 질문의 고유 id (int)
* type : 질문의 유형 (string => 'anonym' | 'real')
* status : 질문의 상태 (string => 'received' | 'accepted' | 'rejected')
* author : 질문 작성자 (number, unique)
* receiver : 질문 받는 유저 (number, unique)
* question : 질문 내용 (varchar(300))
* answer : 질문 답변 (varchar(300))
* createdAt : 질문 생성 시각 (timestamp)
코드 리뷰 부탁드립니당
=> 질문 객체에 대한 schema 정의

.prettierrc, package.json, yarn.lock
=> feat: initialize prettier

prisma/schema.prisma
=> feat: create like model

src/resources/token.ts, src/routes/auth/refresh.controller.ts
#9 수정된 문서도 확인해주세요.
https://documenter.getpostman.com/view/15173777/Uz5DrHi4
=> fix: send refresh token in body

src/middlewares/checkExistingUser.ts, src/routes/user/index.ts, src/routes/user/user.controller.ts
`/user`에 접근하여 자신의 정보를 얻을 수 있습니다. 문서를 확인해주세요.
=> feat: logined user information

package.json, src/config.ts, src/routes/upload/index.ts, src/routes/upload/upload.controller.ts, yarn.lock
.env에 `IMGBB_API`값이 필요합니다. 필요 시 연락주세요.
문서 확인해주세요.
=> feat: upload

src/routes/user/list.controller.ts
=> fix: return function

package.json, prisma/schema.prisma, src/routes/post/answer.controller.ts, src/routes/post/question.controller.ts
#18 
`prisma:push` script 실행해주세요.
=> Fix answer

src/resources/uploadImage.ts, src/routes/user/list.controller.ts, src/types/index.ts
=> Fix list name error

src/routes/user/find.controller.ts
=> fix: id to name

prisma/schema.prisma, src/routes/post/answer.controller.ts, src/routes/post/delete.controller.ts, src/routes/post/index.ts, src/routes/post/reject.controller.ts, src/routes/user/list.controller.ts, src/types/index.ts
기존 `post/answer`에는 이제 답변만 할 수 있습니다.
질문 상태를 변경하기 위해선 `post/delete` 와 `post/reject`를 사용해 주세요. (문서 참고)
=> Question manage

src/routes/user/follow.controller.ts, src/routes/user/followList.controller.ts
follow/following 리스트 전체유저 반환입니다.
=> fix: return all following/follower users

src/routes/post/index.ts, src/routes/post/question.controller.ts
로그인 없이 질문을 등록할 수 있습니다. question 문서 부분을 확인해주세요.
=> fix: question without login

src/routes/user/index.ts, src/routes/user/myQuestions.controller.ts
자신이 한 질문을 가져옵니다. `user/me/questions`부분 문서를 확인해주세요.
=> feat: my questions

src/routes/user/list.controller.ts
=> fix: order answer by answer post time

.dockerignore, .gitignore, Dockerfile, docker-compose.yml, package-lock.json, package.json, yarn.lock
`docker compose --env-file ./.prod.env up -d`
`--env-file` is optional
=> feat: docker

src/resources/liked.ts, src/routes/post/like.controller.ts, src/routes/user/feed.controller.ts, src/routes/user/list.controller.ts, src/routes/user/myQuestions.controller.ts, src/types/index.ts
=> add feed result liked and like count

src/routes/user/feed.controller.ts, src/types/index.ts
#43 #44
고치다보니 팔로워 피드를 불러오는 과정에서 오류를 발견했습니다. 문서를 참고해주세요. 죄송합니다.
=> fix: feed bug

package.json, prisma/schema.prisma
heroku에서 __dirname에 문제가 있는것 같아 다른 url로 대체합니다.
=> Deploy fix

src/routes/post/like.controller.ts
=> fix: like notification question issue

src/routes/notification/notification.controller.ts, src/routes/user/feed.controller.ts
=> fix: notification order
